name: Deploy ECS service

run-name: Deploy ECS service

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS region'
        required: true
        type: string
        default: 'us-east-1'
      tag:
        description: 'Release version'
        required: true
        type: string
      ecr_repository:
        description: 'ECR repository name'
        required: true
        type: string
        default: 'image-recognition-api'
      ecs_service:
        description: 'ECS service name'
        required: true
        type: string
        default: 'image-recognition-api-dev-service'
      task_definition:
        description: 'Task definition name'
        required: true
        type: string
        default: 'image-recognition-api-dev-task'
      ecs_cluster:
        description: 'ECS cluster name'
        required: true
        type: string
        default: 'image-recognition-api-dev-cluster'

jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ inputs.task_definition }} --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ inputs.ecs_service }}
          image: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.ecr_repository }}:${{ inputs.tag }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: ${{ inputs.ecs_service }}
          cluster: ${{ inputs.ecs_cluster }}
          wait-for-service-stability: true
